### ISSUE TITLE
[bug] TaipyGuiWarning: on_action(): 'process_image' is not a valid function.

### ISSUE THREAD

**Issue by abhijeetGithu** [gmarabout/demo-face-dectection#5]
While running the script from Tutorial:  
this error encounter : 
```python
UserWarning: libuv only supports millisecond timer resolution; all times less will be set to 1 ms
TaipyGuiWarning: on_action(): Exception raised in 'process_image()':
OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\objdetect\src\cascadedetect.cpp:1689: error: (-215:Assertion failed) !empty() in function 'cv::CascadeClassifier::detectMultiScale'

TaipyGuiWarning: on_action(): 'process_image' is not a valid function.
```

**Comment by gmarabout** [comment]
Hey @abhijeetGithu  👋🏻
This error occurs when the classifier file hasn't been properly loaded. 
Could you make sure the file `haarcascade_frontalface_default.xml` exists and you run the Python script from the same location? Let me know.

**Comment by abhijeetGithu** [comment]
because of some file mismatch location it was not reading the xml file but now its working fine 
but this model is not giving accurate face results like for some faces it's not recognise tha no. of faces 
can you provide me other detection model which i can use on web for better results.

**Comment by gmarabout** [comment]
Sorry to hear the model does not suit your needs. You can try other models directly from the OpenCV site https://github.com/opencv/opencv/tree/4.x/data/haarcascades.
